# Generated by Django 4.2.3 on 2023-08-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='test',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
