# Generated by Django 4.2.3 on 2023-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='test',
        ),
        migrations.AddField(
            model_name='products',
            name='miqdor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='narx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='turi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='administrator',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
